[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
    "erc4626-tests/=lib/openzeppelin-contracts/lib/erc4626-tests/",  # Add this line
    "halmos-cheatcodes/=lib/openzeppelin-contracts/lib/halmos-cheatcodes/src/" # Add this line
]
# solc_version = "0.8.19"
auto_detect_solc = true
optimizer = true
optimizer_runs = 200
via_ir = false

excluded_paths = [
    "lib/openzeppelin-contracts/certora",
    "lib/openzeppelin-contracts/test",
    "lib/forge-std/test"
]
[rpc_endpoints]
arbitrum_sepolia = "https://sepolia-rollup.arbitrum.io/rpc"

#[etherscan]
#arbitrum_sepolia = { key = "${ARBISCAN_API_KEY}", url = "https://api-sepolia.arbiscan.io/api" }
